#!/bin/bash
APP=${!#}

# The parameter $1 is the backup directory location dedicated to the app
backup_dir=$1


domain=$(sudo yunohost app setting $APP domain)
path=$(sudo yunohost app setting $APP path)
user=$(sudo yunohost app setting $APP allowed_users)
is_public=$(sudo yunohost app setting $APP is_public)

# Copy the app files
final_path=/var/www/$APP
sudo mkdir -p ${backup_dir}/var/www
sudo cp -a $final_path "${backup_dir}/var/www/$APP"

# Copy the conf files
sudo mkdir -p "${backup_dir}/conf"
sudo cp -a /etc/nginx/conf.d/$domain.d/$APP.conf "${backup_dir}/conf/nginx.conf"
sudo cp -a /etc/php5/fpm/pool.d/$APP.conf "${backup_dir}/conf/php-fpm.conf"
