#!/bin/bash
APP=${!#}

domain=$(sudo yunohost app setting $APP domain)

sudo service pure-ftpd-ldap stop
sudo apt-get remove -y -qq pure-ftpd-ldap pure-ftpd-common
sudo yunohost service remove pure-ftpd-ldap

sudo rm -rf /var/www/$APP
sudo rm -f /etc/nginx/conf.d/$domain.d/$APP.conf
sudo rm -f /etc/php5/fpm/pool.d/$APP.conf

sudo service nginx reload
sudo yunohost app ssowatconf
